const ADD_VIDEO = 'ADD_VIDEO'
const ADD_VIDEO_CAPTION = 'ADD_VIDEO_CAPTION'
const FILTER_VIDEOS = 'FILTER_VIDEOS'
const SELECT_VIDEO = 'SELECT_VIDEO'

export {
  ADD_VIDEO,
  ADD_VIDEO_CAPTION,
  FILTER_VIDEOS,
  SELECT_VIDEO
}
